redaction_fields:
  filers:
  - addressList.[].line1
  - addressList.[].line2
  - addressList.[].zip
  - emailList.[].address
  - officers.[].addressList.[].line1
  - officers.[].addressList.[].line2
  - officers.[].addressList.[].zip
  - officers.[].email.address
  - officers.[].phone.number
  - phoneList.[].number
  filings:
  - filerMeta.addressList.[].line1
  - filerMeta.addressList.[].line2
  - filerMeta.addressList.[].zip
  - filerMeta.emailList.[].address
  - filerMeta.phoneList.[].number
  #transactions: []
  #filing_activities: []
  #filing_elements: []
  #elections: []
