client_config_backend: settings
client_config:
  client_id: 228820233409-u1hcjrq7cs5ce0t658raesmp7vl5nbo5.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
