name: "Daily run"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  pull_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: "pip install -r requirements.txt"
    - run: "python pull_and_redact_files.py"
      env:
        REPO_OWNER: ${{ github.repository_owner}}
        NETFILE_API_KEY: ${{ secrets.NETFILE_API_KEY }}
        NETFILE_API_SECRET: ${{ secrets.NETFILE_API_SECRET }}
    - run: "bash bin/push_redacted_files.sh"
      if: ${{ env.SERVICE_ACCOUNT_KEY_JSON == '' }}
      env:
        SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
    - run: "python push_to_gdrive.py"
      if: ${{ env.SERVICE_ACCOUNT_KEY_JSON != '' }}
      env:
        SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
    - run: "python test_pull_from_gdrive.py"
      if: ${{ env.SERVICE_ACCOUNT_KEY_JSON != '' }}
      env:
        SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
        REPO_OWNER: ${{ github.repository_owner}}