name: "Daily run"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
permissions:
  contents: write
jobs:
  pull_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - run: "python pull_and_redact_files.py"
      env:
        REPO_OWNER: ${{ github.repository_owner}}
    - run: "bash bin/push_redacted_files.sh"
