name: "Daily run"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  pull_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - run: "python pull_and_redact_files.py"
      env:
        REPO_NAME: ${{ github.event.repository.name }}
    - run: "bash bin/push_redacted_files.sh"
