name: "Daily run"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  pull_data:
    runs-on: ubuntu-latest
    steps:
    - run: "python pull_and_redact_files.py"
    - run: "bash push_redacted_files.sh"
